In [1]:
from simulator import Simulator
import yaml

config = yaml.safe_load(open('configurations/MNIST/MLP/FedAvg/no_straggle.yaml'))
sim = Simulator(**config)

In [2]:
from aggregators.rfa import geometric_median
import torch

points = [list(sim.global_model.get_state().values())] * 5
median = geometric_median(points)
weights = torch.ones(5)

In [3]:
for components in zip(*points): break 

In [4]:
from aggregators.rfa import weighted_average

weights = torch.ones(len(components)).cuda()

med = geometric_median(components)

In [5]:
med.shape


torch.Size([200, 784])

In [10]:
components[0][0].device

device(type='cuda', index=0)

In [9]:
torch.stack(med).shape

torch.Size([200, 784])

In [8]:
med[0].shape

torch.Size([784])

In [10]:
o[0].shape

torch.Size([784])

In [29]:
weights.reshape(
    [len(points)]+[1]*p[0].ndim
)

tensor([[[1.]],

        [[1.]],

        [[1.]],

        [[1.]],

        [[1.]]])

In [17]:
w[:,None,None]

tensor([[[1.]],

        [[1.]],

        [[1.]]])

In [19]:
w.reshape((3,1,1))

tensor([[[1.]],

        [[1.]],

        [[1.]]])